name: 🚀 Vercel Deployment Workflow

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: 📦 Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: 🛠️ Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use Node.js version 18

      # Step 3: Install dependencies
      - name: 🔨 Install Dependencies
        run: |
          echo -e "\033[33m🔨 Installing dependencies...\033[0m"
          npm install
          echo -e "\033[32m✔️ Dependencies installed successfully!\033[0m"

      # Step 4: Generate vercel.json
      - name: 📝 Generate vercel.json
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          echo -e "\033[36m📝 Generating vercel.json...\033[0m"
          npm run create-vercel.json-file $SITE_URL
          echo -e "\033[32m✔️ vercel.json generated successfully!\033[0m"

      # Step 5: Download the Curriculum Vitae
      - name: 📥 Download Curriculum Vitae
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          echo -e "\033[33m📥 Downloading Curriculum Vitae...\033[0m"
          npm run cv:download $API_SECRET_KEY $SITE_URL
          echo -e "\033[32m✔️ Curriculum vitae downloaded successfully!\033[0m"

      # (Optional) Step 6: Build the Astro project
      # - name: 🚀 Build Astro Project
      #   run: |
      #     echo -e "\033[33m🚀 Building the Astro project...\033[0m"
      #     npm run build
      #     echo -e "\033[32m✔️ Build complete!\033[0m"

      # Step 7: Deploy to Vercel
      - name: 🌐 Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo -e "\033[34m🌐 Deploying to Vercel...\033[0m"
          npx vercel --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes
          echo -e "\033[32m✔️ Deployment successful!\033[0m"

      # Step 8: Clean up sensitive files
      - name: 🧹 Clean Up Sensitive Files
        run: |
          echo -e "\033[31m🧹 Cleaning up sensitive files...\033[0m"
          rm -f vercel.json
          npm cache clean --force
          echo -e "\033[32m✔️ Clean-up complete!\033[0m"
